# Generated by Django 6.0 on 2026-01-08 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
                ('tipo_helado', models.CharField(blank=True, max_length=50, null=True)),
                ('sabor1', models.CharField(blank=True, max_length=50, null=True)),
                ('sabor2', models.CharField(blank=True, max_length=50, null=True)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='ingresos.venta')),
            ],
        ),
    ]
