# Generated by Django 6.0 on 2026-01-02 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0002_producto_cantidad_producto_sabor_producto_tamaño_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(max_length=100)),
                ('cliente_id', models.CharField(max_length=20)),
                ('cliente_celular', models.CharField(max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo_pago', models.CharField(choices=[('contado', 'Pago de contado'), ('pendiente', 'Pago pendiente')], max_length=10)),
                ('metodo_pago', models.CharField(blank=True, max_length=50)),
                ('total', models.FloatField(default=0)),
                ('pendiente', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VentaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamaño', models.CharField(blank=True, max_length=50, null=True)),
                ('sabor', models.CharField(blank=True, max_length=50, null=True)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.FloatField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='ingresos.venta')),
            ],
        ),
    ]
