# Generated by Django 6.0 on 2026-01-11 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='tipo',
            field=models.CharField(choices=[('contado', 'Venta de contado'), ('credito', 'Venta a crédito')], default='contado', max_length=10),
        ),
    ]
