# Generated by Django 6.0 on 2026-01-03 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0001_initial'),
        ('inventario', '0002_producto_cantidad_producto_sabor_producto_tamaño_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('id_cliente', models.CharField(max_length=20, unique=True)),
                ('celular', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='venta',
            name='cliente_celular',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='cliente_id',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='cliente_nombre',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='metodo_pago',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='pendiente',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='tipo_pago',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='total',
        ),
        migrations.AddField(
            model_name='venta',
            name='pago_contado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ingresos.cliente'),
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('tamaño', models.CharField(blank=True, max_length=50, null=True)),
                ('sabor', models.CharField(blank=True, max_length=50, null=True)),
                ('precio_unitario', models.FloatField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingresos.venta')),
            ],
        ),
        migrations.DeleteModel(
            name='VentaProducto',
        ),
    ]
