# Generated by Django 6.0 on 2026-01-11 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0002_venta_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='tipo',
        ),
        migrations.AddField(
            model_name='venta',
            name='tipo_venta',
            field=models.CharField(choices=[('contado', 'Contado'), ('credito', 'Crédito')], default='contado', max_length=10),
            preserve_default=False,
        ),
    ]
