# Generated by Django 6.0 on 2026-01-12 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0003_remove_venta_tipo_venta_tipo_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoventa',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productoventa',
            name='tamaño',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productoventa',
            name='tipo_postre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
