# Generated by Django 6.0 on 2026-01-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0004_productoventa_nombre_productoventa_tamaño_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoventa',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productoventa',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
