# Generated by Django 6.0 on 2026-01-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0005_productoventa_precio_unitario_productoventa_subtotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='total_bs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
